# setup vars
environ:  "dev" # dev || stage || prod
breaking_stuff_is_ok:   true
# NOTE: stage is a production rails env (https://devcenter.heroku.com/articles/deploying-to-a-custom-rails-environment)
rails_env:              "development" # development | test | production

# private vars
login_user_passphrase:  "{{ vault_login_user_passphrase }}"
tomcat_users:           "{{ vault_tomcat_users }}"

# NOTE: on dev, deploy sufia to synced_folder and other installed dependencies elsewhere
# TODO: app_base_deploy_dir (?)
# cross-role vars
sufia_base_deploy_dir:      "/var/www/html"
passenger_base_deploy_dir: "{{ sufia_base_deploy_dir }}"

# ruby vars
ruby_from_source:       true

# sufia role vars
sufia_version:          "7.3.0" # 7.2.0 | 7.3.0.rc1
sufia_mode:             "prod_like" # dev | prod_like
sufia_rebuild:          true
sufia_redeploy:         true
# NOTE: this particular override works for version 7.3.x, but not 7.2.x (which has additional requirements)
# sufia_gems:             "gem 'sufia', '{{ sufia_version }}'"

# database vars
db_provider:            "postgresql"
db_admin_user:          "postgres"
db_create_users:        true
 # TODO: review - is there an expected db username?
db_users:
  - user:               "sufia"
    pass:               "{{ vault_db_password }}"
    flags:              "CREATEDB,NOSUPERUSER"
db_create_databases:    true
db_databases:
  - name:               "sufia"
    encoding:           "UTF-8"
    owner:              "sufia"
postgres_hba_entries:
  - type:               "local"
    database:           "sufia"
    user:               "sufia"
    address:            ""
    method:             "md5"

# solr vars
solr_cores:
  - "hydra-development"
solr_version:           6.4.1
solr_user:              "solr"

# apache vars:
hostname:               "sufia"
domainname:             "test.dev"
apache_remove_welcome:  true
apache_https:           true
ssl_self_sign_cert:     true

# passenger vars
 # TODO: adopt and move up
update_packages: false

# tomcat vars
tomcat_major_version:   7
tomcat_version:         7.0.75
catalina_opts:          "-server
                        -Dcom.sun.management.jmxremote=true"

java_opts:              "-Djava.awt.headless=true
                        -Dfile.encoding=UTF-8
                        -Dfcrepo.home={{ fcrepo_home }}
                        -Dfcrepo.modeshape.configuration=classpath:/config/file-simple/repository.json
                        -Xms{{ minimum_heap_size }}m
                        -Xmx{{ maximum_heap_size }}m
                        -XX:NewSize=256m
                        -XX:MaxNewSize=256m
                        -XX:MetaspaceSize=256m
                        -XX:MaxMetaspaceSize=256m
                        -XX:+DisableExplicitGC"
                        # -Dlogback.configurationFile={{ fcrepo_config_dir }}/logback.xml
